[package]
name = "spelltest"
version = "0.1.2"
authors = ["Fransisco Wijaya <bidipeppercrap@gmail.com>"]
description = "SPELL TEST Mechanics"
repository = "https://github.com/bidipeppercrap/spelltest.rs"
readme = "README.md"
license-file = "LICENSE"

[dependencies]