[package]
name = "spelltest"
version = "0.2.0"
authors = ["Fransisco Wijaya <bidipeppercrap@gmail.com>"]
edition = "2018"
description = "SPELL TEST Mechanics"
repository = "https://github.com/bidipeppercrap/spelltest.rs"
readme = "README.md"
license-file = "LICENSE"

[dependencies]
